apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  tokenRolesPath: {{ .Values.config.tokenRolesPath }}
  tokenContextPath: {{ .Values.config.tokenContextPath }}
  identityProviderOidURL: {{ .Values.config.identityProviderOidURL }}
{{- range $k, $v := .Values.config.tsaURLs }}
  {{ $k }}: {{ $v }}
{{ end }}